// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/projects": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/projects";
  };
  "./layouts/MainLayout.jsx": {
    id: "layouts/MainLayout";
    page: "/" | "/about" | "/projects";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "./routes/projects.tsx": {
    id: "routes/projects";
    page: "/projects";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "layouts/MainLayout": typeof import("./app/./layouts/MainLayout.jsx");
  "routes/home": typeof import("./app/./routes/home.tsx");
  "routes/about": typeof import("./app/./routes/about.tsx");
  "routes/projects": typeof import("./app/./routes/projects.tsx");
};